[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "0.11.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/sethvargo/go-diceware"

[[constraint]]
  name = "github.com/sethvargo/go-password"
  version = "0.1.1"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
